### ISSUE TITLE
aarch64-apple-darwin support

### ISSUE THREAD

**Issue by FreeMasen** [mbround18/setup-osxcross#8]
Would it be possible to use this action to build for the `aarch64-apple-darwin` target?

**Comment by mbround18** [comment]
Released in v3 — aarch64-apple-darwin is now auto-configured alongside x86_64-apple-darwin whenever the SDK you point at supports it (11.0+, e.g. 12.3):

```yaml
- uses: mbround18/setup-osxcross@v3
  with:
    osx-version: "12.3"

- run: cargo build --release --target aarch64-apple-darwin
```

While in there I also fixed a couple of things CI had been silently hiding for months: `RUSTFLAGS` was embedding an invalid `-C ar=` flag that would've broken real cross-compiles, and the demo workflow itself had been failing on every push (dead third-party action, deprecated upload-artifact). Both x86_64 and aarch64 cross-builds are now verified green in CI: https://github.com/mbround18/setup-osxcross/actions/runs/32067892044
